export const styles = {
  page: {
    minHeight: '100vh',
    padding: 16,
    fontFamily: 'system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif',
    background: '#fff',
    color: '#111',
  } as const,
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '12px 12px',
    border: '2px solid #1e1e1e',
    borderRadius: 12,
    background: '#fff3bf',
  } as const,
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  } as const,
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  } as const,
  grid: {
    marginTop: 16,
    display: 'grid',
    gridTemplateColumns: 'minmax(360px, 1fr) minmax(360px, 1fr)',
    gap: 16,
    alignItems: 'stretch',
  } as const,
  panel: {
    border: '2px solid #1e1e1e',
    borderRadius: 12,
    padding: 12,
    background: '#ffffff',
  } as const,
  leftCol: {
    border: '2px solid #1e1e1e',
    borderRadius: 12,
    padding: 12,
    background: '#a5d8ff',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    minHeight: 640,
  } as const,
  rightCol: {
    border: '2px solid #1e1e1e',
    borderRadius: 12,
    padding: 12,
    background: '#c3fae8',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    minHeight: 640,
  } as const,
  pillRow: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  } as const,
  pill: {
    border: '2px solid #1e1e1e',
    borderRadius: 999,
    padding: '6px 10px',
    background: '#fff',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 13,
  } as const,
  monoBox: {
    border: '2px solid #1e1e1e',
    borderRadius: 12,
    padding: 12,
    background: '#fff',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 13,
    whiteSpace: 'pre-wrap',
    lineHeight: 1.35,
  } as const,
  bottom: {
    marginTop: 16,
    border: '2px solid #1e1e1e',
    borderRadius: 12,
    padding: 12,
    background: '#d0bfff',
  } as const,
};
